from django.urls import path
from hospitalapp import views
urlpatterns=[
    path('',views.index),
    path('login',views.login),
    path('adminindex',views.adminindex),
    path('managedepartment',views.managedepartment),
    path('delete',views.delete),
    path('managehr',views.managehr),
    path('deletehr',views.deletehr),
    path('edithr',views.edithr),
    path('hrindex',views.hrindex),
    path('managemedicalsupredent',views.managemedicalsupredent),
    path('deletemedical',views.deletemedical),
    path('editmedical',views.editmedical),
    path('managedoctor',views.managedoctor),
    path('deletedoctor',views.deletedoctor),
    path('editdoctor',views.editdoctor),
    path('managepharmacy',views.managepharmacy),
    path('deletepharmacy',views.deletepharmacy),
    path('editpharmacy',views.editpharmacy),
    path('managereception',views.managereception),
    path('deletereception',views.deletereception),
    path('editreception',views.editreception),
    path('approval',views.approval),
    path('medicalapproval',views.medicalapproval),
    path('doctorapproval',views.doctorapproval),
    path('doctorapprovalu',views.doctorapprovalu),
    path('pharmacyapproval',views.pharmacyapproval),
    path('pharmacyapprovalu',views.pharmacyapprovalu),
    path('receptionapproval',views.receptionapproval),
    path('receptionapprovalu',views.receptionapprovalu),
    path('medicalsupredentprofile',views.medicalsupredentprofile),
    path('doctorprofile',views.doctorprofile),
    path('receptionprofile',views.receptionprofile),
    path('pharmacyprofile',views.pharmacyprofile),
    path('managepatient',views.managepatient),
    path('deletepatient',views.deletepatient),
    path('editpatient',views.editpatient),
    path('patientobservation',views.patientobservation),
    path('deletepatientobservation',views.deletepatientobservation),
    path('editpatientobservation',views.editpatientobservation),
    path('patientconsultation',views.patientconsultation),
    path('patientconsultationdoctor',views.patientconsultationdoctor),
    path('patientconsultationappointment',views.patientconsultationappointment),
    path('patientobservationview',views.patientobservationview),
    path('addmedicine',views.addmedicine),
    path('addstock',views.addstock),
    path('addstockr',views.addstockr),
    path('prescription',views.prescription),
    path('prescriptiont',views.prescriptiont),
    path('prescriptiontt',views.prescriptiontt),
    path('addmedicinedelete',views.addmedicinedelete),
    path('addmedicineedit',views.addmedicineedit),
    path('stockdelete',views.stockdelete),
    path('pharmacybilling',views.pharmacybilling),
    path('patientprofile',views.patientprofile),
    path('consultationp',views.consultationp),
    path('complaintp',views.complaintp),
    path('addpharmacy',views.addpharmacy),
    path('patientcomplaint',views.patientcomplaint),
    path('stock',views.stock),
    path('stockcollection',views.stockcollection),
    path('bill',views.bill),
    path('patientdate',views.patientdate),
    path('patientdatee',views.patientdatee),
    path('billing',views.billing),
    path('billingt',views.billingt),
    path('finish',views.finish),
    path('consultationf',views.consultationf),
    path('managepatientdisplay',views.managepatientdisplay),





]


